# Generated by Django 5.2.14 on 2026-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacion',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AlterField(
            model_name='observacion',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
